// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"crypto/tls"
	"net/http"

	errors "github.com/go-openapi/errors"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	graceful "github.com/tylerb/graceful"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"

	"github.com/ljdursi/openapi_calls_example/go/restapi/operations"
	"github.com/ljdursi/openapi_calls_example/models"
)

// This file is safe to edit. Once it exists it will not be overwritten

//go:generate swagger generate server --target .. --name  --spec ../swagger.yaml

func configureFlags(api *operations.VariantsAndCallsAPIDemoAPI) {
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ ... }
}

func configureAPI(api *operations.VariantsAndCallsAPIDemoAPI) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	// api.Logger = log.Printf

	api.JSONConsumer = runtime.JSONConsumer()

	api.JSONProducer = runtime.JSONProducer()

	api.MainGetCallsHandler = operations.MainGetCallsHandlerFunc(func(params operations.MainGetCallsParams) middleware.Responder {
		return middleware.NotImplemented("operation .MainGetCalls has not yet been implemented")
	})
	api.MainGetIndividualsHandler = operations.MainGetIndividualsHandlerFunc(func(params operations.MainGetIndividualsParams) middleware.Responder {
		return middleware.NotImplemented("operation .MainGetIndividuals has not yet been implemented")
	})
	api.MainGetIndividualsByVariantHandler = operations.MainGetIndividualsByVariantHandlerFunc(func(params operations.MainGetIndividualsByVariantParams) middleware.Responder {
		return middleware.NotImplemented("operation .MainGetIndividualsByVariant has not yet been implemented")
	})
	api.MainGetVariantsHandler = operations.MainGetVariantsHandlerFunc(func(params operations.MainGetVariantsParams) middleware.Responder {
		return middleware.NotImplemented("operation .MainGetVariants has not yet been implemented")
	})
	api.MainGetVariantsByIndividualHandler = operations.MainGetVariantsByIndividualHandlerFunc(func(params operations.MainGetVariantsByIndividualParams) middleware.Responder {
		return middleware.NotImplemented("operation .MainGetVariantsByIndividual has not yet been implemented")
	})
	api.MainPutCallHandler = operations.MainPutCallHandlerFunc(func(params operations.MainPutCallParams) middleware.Responder {
		return middleware.NotImplemented("operation .MainPutCall has not yet been implemented")
	})
	api.MainPutIndividualHandler = operations.MainPutIndividualHandlerFunc(func(params operations.MainPutIndividualParams) middleware.Responder {
		return middleware.NotImplemented("operation .MainPutIndividual has not yet been implemented")
	})
	api.MainPutVariantHandler = operations.MainPutVariantHandlerFunc(func(params operations.MainPutVariantParams) middleware.Responder {
		return middleware.NotImplemented("operation .MainPutVariant has not yet been implemented")
	})

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *graceful.Server, scheme, addr string) {
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}
