swagger: '2.0'
info:
  title: Variants and Calls API demo
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /variants:
    get:
      x-swagger-router-controller: main
      operationId: get_variants
      summary: Get all variants within genomic range
      parameters:
        - name: chromosome
          in: query
          type: string
          pattern: "^[a-zA-Z0-9]*$"
          x-example: "chr1"
        - name: start
          in: query
          type: integer
          minimum: 1
          x-example: 1
        - name: end
          in: query
          type: integer
          x-example: 100000
      responses:
        '200':
          description: Return variants
          schema:
            type: array
            items:
              $ref: '#/definitions/Variant'
    post:
      x-swagger-router-controller: main
      operationId: post_variant
      summary: Add a variant to the database
      parameters:
        - name: variant
          in: body
          schema:
            $ref: '#/definitions/Variant'
      responses:
        '201':
          description: New variant created
          headers:
            Location:
              type: string
              format: url
        '405':
          description: Cannot overwrite variant

  /variants/{variant_id}:
    get:
      x-swagger-router-controller: main
      operationId: get_variant
      summary: Get specific variant
      parameters:
        - $ref: '#/parameters/variant_id'
      responses:
        "200":
          description: Return variant
          schema:
            $ref: '#/definitions/Variant'
        "404":
          description: Variant not found


  /individuals:
    get:
      x-swagger-router-controller: main
      operationId: get_individuals
      summary: Get all individuals
      responses:
        '200':
          description: Return individuals
          schema:
            type: array
            items:
              $ref: '#/definitions/Individual'
    post:
      x-swagger-router-controller: main
      operationId: post_individual
      summary: Add an individual to the database
      parameters:
        - name: individual
          in: body
          schema:
            $ref: '#/definitions/Individual'
      responses:
        '201':
          description: New individual created
          headers:
            Location:
              type: string
              format: url
        '405':
          description: Cannot overwrite individual

  /individuals/{individual_id}:
    get:
      x-swagger-router-controller: main
      operationId: get_individual
      summary: Get specific individual
      parameters:
        - $ref: '#/parameters/individual_id'
      responses:
        "200":
          description: Return individual
          schema:
            $ref: '#/definitions/Individual'
        "404":
          description: Individual not found

  /calls:
    get:
      x-swagger-router-controller: main
      operationId: get_calls
      summary: Get all calls
      responses:
        '200':
          description: Return calls
          schema:
            type: array
            items:
              $ref: '#/definitions/Call'
    post:
      x-swagger-router-controller: main
      operationId: post_call
      summary: Add a call to the database
      parameters:
        - name: call
          in: body
          schema:
            $ref: '#/definitions/Call'
      responses:
        '201':
          description: New call created
          headers:
            Location:
              type: string
              format: url
        '405':
          description: Invalid call

  /calls/{call_id}:
    get:
      x-swagger-router-controller: main
      operationId: get_call
      summary: Get specific call
      parameters:
        - $ref: '#/parameters/call_id'
      responses:
        "200":
          description: Return call
          schema:
            $ref: '#/definitions/Call'
        "404":
          description: Call not found

parameters:
  variant_id:
    name: variant_id
    description: Variant unique identifier
    in: path
    type: integer
    required: true
    x-example: 1

  individual_id:
    name: individual_id
    description: Individual unique identifier
    in: path
    type: integer
    required: true
    x-example: 1

  call_id:
    name: call_id
    description: Call unique identifier
    in: path
    type: integer
    required: true
    x-example: 1


definitions:
  Individual:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        description: Unique identifier
        example: 1
      description:
        type: string
        description: description of individual
        example: "Subject 17"
        minLength: 1
        maxLength: 100

  Call:
    type: object
    required:
      - individual_id
      - variant_id
      - genotype
    properties:
      id:
        type: integer
        description: Unique identifier
        example: 1
      individual_id:
        type: integer
        description: Unique identifier of individual
        example: 1
      variant_id:
        type: integer
        description: Unique identifier of variant
        example: 1
      genotype:
        type: string
        description: Called genotype
        example: "0/1"
      format:
        type: string
        description: Additional call information
        example: "GQ:DP:HQ 48:1:51,51"
        minLength: 0
        maxLength: 100
        default: ""

  Variant:
    type: object
    required:
      - chromosome
      - start
      - ref
      - alt
    properties:
      id:
        type: integer
        description: Unique identifier
        example: 1
      name:
        type: string
        description: variant name if any
        example: "rs6054257"
        minLength: 0
        maxLength: 100
        default: ""
      chromosome:
        type: string
        description: Chromosome variant occurs on
        example: "chr1"
        minLength: 1
        maxLength: 10
      start:
        type: integer
        description: Beginning location of variant (1-indexed, like VCF)
        example: 14370
      ref:
        type: string
        description: Reference bases
        example: "G"
      alt:
        type: string
        description: Alternate (variant) vases
        example: "A"
